#version: "3.9"
#services:
#  frontend:
#    image: nginx:alpine
#    networks:
#      - app-network
#    volumes:
#      - ./frontend/dist:/usr/share/nginx/html
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./frontend1/certs:/etc/ssl
#    ports:
#      - "443:443"
#    depends_on:
#      - gateway
#
#  gateway:
#    image: maalami/springbootgateway:latest
#    expose:
#      - "8442"
#    networks:
#      - app-network
#networks:
#  app-network:
#    driver: bridge
services:
  frontend:
    image: maalami/springbootstorefrontend
    ports:
      - "443:443"
    depends_on:
      - gateway

  gateway:
    image: maalami/springbootgateway:latest
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mundialmente1
    restart: always
    depends_on:
      - store
      - db
    ports:
      - "8442:8442"
  store:
    build:
      dockerfile: Dockerfile
    image: maalami/springbootstore:latest
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/items
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mundialmente1
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=Mundialmente1
      - MYSQL_DATABASE=items
    restart: always
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
